name:                numberedQueue
version:             0.1.0.0
github:              "tjlaxs/numberedQueue"
license:             BSD3
author:              "Tero Laxström"
maintainer:          "tlax@neonpeons.com"
copyright:           "2020 Tero Laxström"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tjlaxs/numberedQueue#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- text
- say
- warp
- wai
- http-types

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  numberedQueue-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - numberedQueue

tests:
  numberedQueue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - numberedQueue
